- name: install the latest version of psql
  yum:
    name: postgresql
    state: latest
    
- name: install the latest version of python-devel
  yum:
    name: python-devel
    state: latest
    
- name: upgrade pip
  raw: pip install --upgrade pip
    
- name: Install psycopg2-binary
  raw: pip install psycopg2-binary
#  when: check_python.rc != 0


- name: Remove database 
  postgresql_db:
    login_host: "{{alfresco.database.host}}"
    name: "{{alfresco.database.name}}"
    login_user: "{{alfresco.database.user}}"
    login_password: "{{alfresco.database.password}}"
    owner: "{{alfresco.database.user}}"
    state: absent
    
- name: Create a new database 
  postgresql_db:
    login_host: "{{alfresco.database.host}}"
    name: "{{alfresco.database.name}}"
    login_user: "{{alfresco.database.user}}"
    login_password: "{{alfresco.database.password}}"
    owner: "{{alfresco.database.user}}"
    encoding: UTF-8
    state: present
    
- name: Restore a database 
  postgresql_db:
    login_host: "{{alfresco.database.host}}"
    name: "{{alfresco.database.name}}"
    login_user: "{{alfresco.database.user}}"
    login_password: "{{alfresco.database.password}}"
    owner: "{{alfresco.database.user}}"
    encoding: UTF-8
    state: restore
    target: "{{data_dumpfile}}"
